name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'components/**'
      - 'layouts/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.js'
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Prepare and deploy
        run: |
          # Ensure .nojekyll and CNAME files exist
          touch out/.nojekyll
          echo "shrix.com" > out/CNAME
          
          # Copy the built files to the root directory
          cp -r out/* .
          cp out/.nojekyll .
          
          # Configure Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Commit and push changes
          git add .
          git commit -m "Deploy Next.js app to GitHub Pages" || echo "No changes to commit"
          git push 