name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'components/**'
      - 'layouts/**'
      - 'lib/**'
      - 'public/**'
      - 'next.config.js'
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Prepare for deployment
        run: |
          # Create a temporary directory for the build output
          mkdir -p tmp_deploy
          
          # Copy the built Next.js app to the temporary directory
          cp -r out/* tmp_deploy/
          
          # Ensure .nojekyll file exists
          touch tmp_deploy/.nojekyll
          
          # Ensure CNAME file exists
          echo "shrix.com" > tmp_deploy/CNAME
          
          # Preserve the .git directory and important files from the main branch
          git checkout-index -a -f --prefix=tmp_deploy/
          
          # Move the temporary directory contents to the root
          cp -r tmp_deploy/* .
          cp -r tmp_deploy/.nojekyll .
          
          # Clean up
          rm -rf tmp_deploy
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Next.js app to GitHub Pages" || echo "No changes to commit"
          git push 